# Generated by Django 5.1.1 on 2024-10-15 16:26

import webpfield.fields
import webpfield.webp_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('coverMobile', webpfield.fields.WebPField(storage=webpfield.webp_storage.WebPStorage(), upload_to='', verbose_name='Обложка для мобильный устройств')),
                ('coverDesktop', webpfield.fields.WebPField(storage=webpfield.webp_storage.WebPStorage(), upload_to='', verbose_name='Обложка для компьютерных устройств')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер отображения')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order'],
            },
        ),
    ]
