# Generated by Django 5.1.1 on 2024-10-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('coverMobile', models.ImageField(upload_to='', verbose_name='Обложка для мобильный устройств')),
                ('coverDesktop', models.ImageField(upload_to='', verbose_name='Обложка для компьютерных устройств')),
            ],
        ),
    ]
