# Generated by Django 5.1.1 on 2024-10-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Проекты'},
        ),
    ]
