# Generated by Django 5.1.1 on 2024-10-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
