# Generated by Django 5.1.1 on 2024-10-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_alter_project_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Секция: "О проектах"',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='section',
            field=models.ManyToManyField(related_name='projects', to='landing.projectssection', verbose_name='Секция'),
        ),
    ]
