# Generated by Django 5.1.1 on 2024-10-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_alter_project_options_project_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30, verbose_name='Полное имя')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('avatar', models.ImageField(upload_to='', verbose_name='Аватарка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер отображения')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Члены команды',
                'ordering': ['order'],
            },
        ),
    ]
