# Generated by Django 5.1.1 on 2024-10-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogType', models.CharField(max_length=30, verbose_name='og:type')),
                ('ogTitle', models.CharField(max_length=70, verbose_name='og:title')),
                ('ogUrl', models.URLField(verbose_name='og:url')),
                ('ogImage', models.ImageField(upload_to='', verbose_name='og:image')),
                ('ogDescription', models.TextField(max_length=100, verbose_name='og:description')),
            ],
        ),
    ]
