# Generated by Django 5.1.1 on 2024-10-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_seo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'SEO', 'verbose_name_plural': 'SEO'},
        ),
    ]
