# Generated by Django 5.1.1 on 2024-10-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_alter_seo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsappUrl', models.URLField(verbose_name='Ссылка на whatsapp аккаунт/бот')),
                ('telegramUrl', models.URLField(verbose_name='Ссылка на telegram аккаунт/бот')),
                ('displayedPhoneNumber', models.CharField(max_length=20, verbose_name='Отображаемый номер телефона')),
                ('phoneNumber', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('radioSrc', models.URLField(verbose_name='Ссылка на на источник радио')),
            ],
            options={
                'verbose_name': 'Секция "Контакты и радио"',
                'verbose_name_plural': 'Секция "Контакты и радио"',
            },
        ),
    ]
