# Generated by Django 5.1.1 on 2024-10-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_contactradio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactradio',
            name='radioSrc',
            field=models.URLField(verbose_name='Ссылка на источник радио'),
        ),
    ]
