# Generated by Django 5.1.1 on 2024-10-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_alter_contactradio_radiosrc'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=30, verbose_name='Текст ссылки')),
                ('url', models.CharField(verbose_name='URL-ссылки')),
            ],
            options={
                'verbose_name': 'Ссылка навигации',
                'verbose_name_plural': 'Ссылки навигации',
            },
        ),
    ]
