# Generated by Django 5.1.1 on 2024-10-15 15:50

import webpfield.fields
import webpfield.webp_storage
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0016_alter_navlink_options_navlink_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='avatar',
            field=webpfield.fields.WebPField(storage=webpfield.webp_storage.WebPStorage(), upload_to='', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='project',
            name='coverDesktop',
            field=webpfield.fields.WebPField(storage=webpfield.webp_storage.WebPStorage(), upload_to='', verbose_name='Обложка для компьютерных устройств'),
        ),
        migrations.AlterField(
            model_name='project',
            name='coverMobile',
            field=webpfield.fields.WebPField(storage=webpfield.webp_storage.WebPStorage(), upload_to='', verbose_name='Обложка для мобильный устройств'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='ogImage',
            field=webpfield.fields.WebPField(storage=webpfield.webp_storage.WebPStorage(), upload_to='', verbose_name='og:image'),
        ),
    ]
