# Generated by Django 5.1.1 on 2024-10-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_alter_people_avatar_alter_project_coverdesktop_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Seo',
        ),
    ]
