# Generated by Django 5.1.1 on 2024-10-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0018_delete_project_delete_seo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactRadio',
        ),
        migrations.DeleteModel(
            name='NavLink',
        ),
        migrations.DeleteModel(
            name='OrderAdvertising',
        ),
    ]
