# Generated by Django 5.1.1 on 2024-10-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0019_delete_contactradio_delete_navlink_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
    ]
