# Generated by Django 5.1.1 on 2024-10-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaschool',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
    ]
