# Generated by Django 5.1.1 on 2024-10-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_school', '0003_alter_mediaschool_buttoncaption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaschool',
            name='buttonCaption',
            field=models.CharField(max_length=20, verbose_name='Надпись в кнопке'),
        ),
        migrations.AlterField(
            model_name='mediaschool',
            name='buttonLink',
            field=models.URLField(verbose_name='Ссылка для кнопки'),
        ),
    ]
