# Generated by Django 5.1.1 on 2024-10-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.TextField(verbose_name='Скрипт метрики')),
            ],
            options={
                'verbose_name': 'Метрика',
                'verbose_name_plural': 'Метрика',
            },
        ),
    ]
