# Generated by Django 5.1.1 on 2024-10-17 18:06

import django.db.models.deletion
import webpfield.fields
import webpfield.webp_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Effectiveness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('signature', models.CharField(max_length=20, verbose_name='Подпись')),
                ('coverDesktop', webpfield.fields.WebPField(storage=webpfield.webp_storage.WebPStorage(), upload_to='', verbose_name='Изображение')),
                ('buttonLink', models.URLField(verbose_name='Ссылка для кнопки')),
                ('buttonCaption', models.CharField(default='', max_length=100, verbose_name='Надпись в кнопке для компьютерной версии')),
                ('buttonCaptionMobile', models.CharField(default='', max_length=100, verbose_name='Надпись в кнопке для мобильной версии')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
            },
        ),
        migrations.CreateModel(
            name='EfficiencyBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='Надпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер отображения')),
                ('effectiveness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='effectiveness.effectiveness', verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Бейдж с выгодой',
                'verbose_name_plural': 'Бейджы с выгодой',
                'ordering': ['order'],
            },
        ),
    ]
