# Generated by Django 5.1.1 on 2024-10-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsappUrl', models.URLField(verbose_name='Ссылка на whatsapp аккаунт/бот')),
                ('telegramUrl', models.URLField(verbose_name='Ссылка на telegram аккаунт/бот')),
                ('displayedPhoneNumber', models.CharField(max_length=20, verbose_name='Отображаемый номер телефона')),
                ('phoneNumber', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('radioSrc', models.URLField(verbose_name='Ссылка на источник радио')),
            ],
            options={
                'verbose_name': 'Контакты и радио',
                'verbose_name_plural': 'Контакты и радио',
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=30, verbose_name='Текст ссылки')),
                ('url', models.CharField(verbose_name='URL-ссылки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер отображения')),
            ],
            options={
                'verbose_name': 'Ссылка навигации',
                'verbose_name_plural': 'Ссылки навигации',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OrderAdvertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=30, verbose_name='Текст ссылки')),
                ('url', models.CharField(verbose_name='URL-ссылки')),
            ],
            options={
                'verbose_name': 'Кнопка заказа рекламы',
                'verbose_name_plural': 'Кнопка заказа рекламы',
            },
        ),
    ]
