# Generated by Django 5.1.1 on 2024-10-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinksForAdvertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=40, verbose_name='Название ссылки')),
                ('value', models.CharField(verbose_name='Текст ссылки')),
                ('url', models.CharField(verbose_name='URL-ссылки')),
            ],
            options={
                'verbose_name': 'Ссылка для рекламы',
                'verbose_name_plural': 'Ссылки для рекламы',
            },
        ),
        migrations.CreateModel(
            name='LinksForContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=40, verbose_name='Название ссылки')),
                ('value', models.CharField(verbose_name='Текст ссылки')),
                ('url', models.CharField(verbose_name='URL-ссылки')),
            ],
            options={
                'verbose_name': 'Ссылка для контактов',
                'verbose_name_plural': 'Ссылка для контактов',
            },
        ),
    ]
