# Generated by Django 5.1.1 on 2024-10-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linksforadvertising',
            options={'ordering': ['order'], 'verbose_name': 'Ссылка для рекламы', 'verbose_name_plural': 'Ссылки для рекламы'},
        ),
        migrations.AlterModelOptions(
            name='linksforcontact',
            options={'ordering': ['order'], 'verbose_name': 'Ссылка для контактов', 'verbose_name_plural': 'Ссылка для контактов'},
        ),
        migrations.AddField(
            model_name='linksforadvertising',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер отображения'),
        ),
        migrations.AddField(
            model_name='linksforcontact',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер отображения'),
        ),
    ]
