# Generated by Django 5.1.1 on 2024-10-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0003_footercaption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footercaption',
            name='caption',
            field=models.TextField(max_length=250, verbose_name='Подпись'),
        ),
    ]
