# Generated by Django 5.1.1 on 2024-10-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0004_alter_footercaption_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Условия пользовательского соглашения')),
                ('personal_data', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Согласие на обработку персональных данных')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
            },
        ),
    ]
